### ISSUE TITLE
SAMR34 , Platform IO Hex/bin/elf does not work with custom board 

### ISSUE THREAD

**Issue by Krunal090** [Wiz-IO/platform-sam-lora#3]
Hello Everyone ,
I am new for Platform IO.
I have SAMR34 Xplained Pro Evaluation Kit and program run perfect with inbuilt EDBG chip with platform IO with Visual code studio.
Now i will load same hex in custom board with j-link EDU from atmel studio then SAMR34 not initiated . But if I make sample code in ATMEL studio then hardware run perfect.
So let me know the solution which i have made in SAMR34 Xplained Pro Evaluation Kit and how can i load that hex file in Custom developed board to make it run.

@pfeerick please check .

**Comment by Wiz-IO** [comment]
Hi
I not have J-LINK and custom module to test

**Comment by Krunal090** [comment]
OK so if find any solution let us know ... Thanks

**Comment by Wiz-IO** [comment]
https://www.youtube.com/watch?v=bB29z8-Modg&ab_channel=GeorgiAngelov
soon
