### ISSUE TITLE
Modify the builder / uploader for alternative programmers

### ISSUE THREAD

**Issue by Jakub-Nagy** [Wiz-IO/platform-sam-lora#4]
Hello everyone,
I have tried various cores for the SAM R34, but I like this very much because it supports PlatformIO, which is great.

A large disadvantage is that it only works with the EDBG chip found on the Xplained Pro board, but not on most custom implementations of the chip.

The question is, what would it take to modify the uploader script to make this work with either Jlink or with a UF2 bootloader? I'm assuming that the compilation wouldn't need to be changed. Can you point me to any resources that guide on how to do this? I'm willing to do this and also have other developers to do this, but we're struggling to find the resources. Thanks.

**Comment by Wiz-IO** [comment]
Hi
https://github.com/Wiz-IO/platform-sam-lora/blob/master/builder/frameworks/arduino-samr34.py#L14
is PIO uploading entry point 

https://github.com/Wiz-IO/platform-sam-lora/blob/master/builder/frameworks/arduino-samr34.py#L20
call EDBG uploader

https://github.com/Wiz-IO/platform-sam-lora/blob/master/builder/frameworks/arduino-samr34.py#L16
call custom boot load

**Comment by Jakub-Nagy** [comment]
Thank you for the info.

[This](https://www.github.com/Wiz-IO/platform-sam-lora/tree/master/builder%2Fframeworks%2Fcommon.py#L53) should be the definition of the EDBG uploader, correct?

I was looking at platform-atmelsam to find a similar definition. I found this jlink uploader [here](https://github.com/platformio/platform-atmelsam/blob/develop/builder/main.py#L178). Could that be implemented instead of the current atprogram?

**Comment by Wiz-IO** [comment]
yep... 
edit and test  
platform files is in
C:\Users\USER_NAME\.platformio\platforms\sam-lora\builder\frameworks

**Comment by Wiz-IO** [comment]
soon - Pickit4 and CMSIS-DAP & OpenOCD
https://www.youtube.com/watch?v=bB29z8-Modg&ab_channel=GeorgiAngelov
