### ISSUE TITLE
WLR089 Xplained Pro, PlatformIO, Arduino, not work

### ISSUE THREAD

**Issue by lucasmaziero** [Wiz-IO/platform-sam-lora#5]
Hi
I have WLR089 Xplained Pro Kit, working with framework arduino, build without errors, upload normally, but not running in WLR089 Xplained Pro, not print serial, not blink LED onboard, nothing works.

But if I make code in Microchip Studio run perfectly.

Does anyone have any solution for this problem?

**Comment by Wiz-IO** [comment]
Hi
I not have idea what is the difference between the two boards

**Comment by Wiz-IO** [comment]
Work fine... tested on Win7 & Win10 with simple CMSIS-DAP and Pickit4
